[package]
name = "ch_03_fibonnaci"
version = "0.1.0"
authors = ["Vojislav Grujić <vojislav.grujic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
